environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_GEN: Visual Studio 14 2015
      #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      #VS_GEN: Visual Studio 15 2017

install:
  - appveyor-retry appveyor DownloadFile https://github.com/xianyi/OpenBLAS/files/725155/libs.zip
  - mkdir C:\Libraries\openblas
  - 7z x libs.zip -oC:\Libraries\openblas > nul

  - appveyor-retry appveyor DownloadFile https://sourceforge.net/projects/swig/files/swigwin/swigwin-3.0.12/swigwin-3.0.12.zip
  - 7z x swigwin-3.0.12.zip -oC:\Libraries > nul

  - appveyor-retry appveyor DownloadFile https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-win32-x86.zip
  - 7z x cmake-3.19.1-win32-x86.zip -oC:\Libraries > nul
  - set PATH=C:\Libraries\cmake-3.19.1-win32-x86\bin;%PATH%
  - cmake --version

  - appveyor-retry appveyor DownloadFile https://github.com/devernay/cminpack/archive/v1.3.6.zip
  - 7z x v1.3.6.zip -oC:\Libraries > nil
  - pushd C:\Libraries\cminpack-1.3.6
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\cminpack -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF .
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone --depth 1 https://bitbucket.org/dbarbier/ot-superbuild.git

  - appveyor-retry appveyor DownloadFile http://xmlsoft.org/sources/libxml2-sources-2.9.5.tar.gz
  - 7z x libxml2-sources-2.9.5.tar.gz > nul
  - 7z x libxml2-sources-2.9.5.tar -oC:\Libraries > nul
  - copy ot-superbuild\libxml2.cmake\CMakeLists.txt C:\Libraries\libxml2-2.9.5
  - pushd C:\Libraries\libxml2-2.9.5
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\libxml2 -DBUILD_SHARED_LIBS=OFF .
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone --depth 1 https://github.com/stevengj/nlopt.git
  - pushd nlopt
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\nlopt -DBUILD_SHARED_LIBS=OFF .
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone --depth 1 https://github.com/wjakob/tbb.git
  - pushd tbb
  - cmake -G"%VS_GEN%" -DCMAKE_INSTALL_PREFIX=C:\Libraries\tbb -DTBB_BUILD_TESTS=OFF -DTBB_BUILD_STATIC=OFF .
  - cmake --build . --config Release --target install
  - cd %APPVEYOR_BUILD_FOLDER%

  - appveyor-retry appveyor DownloadFile https://sourceforge.net/projects/gnuwin32/files/diffutils/2.8.7-1/diffutils-2.8.7-1-bin.zip
  - 7z x diffutils-2.8.7-1-bin.zip -oC:\Libraries > nul
  - set PATH=C:\Libraries\bin;%PATH%

  # for sh, tr, cat ...
  - del C:\msys64\usr\bin\python.exe
  - set PATH=C:\msys64\usr\bin;%PATH%
  - python -V
  - diff -v 

build_script:
  - mkdir build && cd build
  - cmake -G"%VS_GEN%" \
      -DCMAKE_INSTALL_PREFIX=%CD:\=/%/install \
      -DBOOST_ROOT="C:/Libraries/boost_1_69_0" \
      -DLAPACK_LIBRARIES="C:/Libraries/openblas/libopenblas.dll.a" \
      -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="/OPT:NOREF /INCREMENTAL:NO" \
      -DUSE_HMAT=OFF \
      -DUSE_BISON=OFF \
      -DSWIG_EXECUTABLE="C:/Libraries/swigwin-3.0.12/swig.exe" \
      -DUSE_COTIRE=ON -DCOTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES="-j4" \
      -DTBB_LIBRARY=C:/Libraries/tbb/lib/tbb.lib -DTBB_INCLUDE_DIR=C:/Libraries/tbb/include \
      -DNLOPT_LIBRARY=C:/Libraries/nlopt/lib/nlopt.lib -DNLOPT_INCLUDE_DIR=C:/Libraries/nlopt/include \
      -DCMINPACK_LIBRARY=C:/Libraries/cminpack/lib/cminpack_s.lib -DCMINPACK_INCLUDE_DIR=C:/Libraries/cminpack/include/cminpack-1 \
      -DLIBXML2_LIBRARIES=C:/Libraries/libxml2/lib/libxml2.lib -DLIBXML2_INCLUDE_DIR=C:/Libraries/libxml2/include \
      ..
  - cmake --build . --config Release --target install
  - set PYTHONPATH=%cd%\install\Lib\site-packages
  - copy install\bin\OT.dll install\Lib\site-packages\openturns
  - copy C:\Libraries\openblas\libopenblas.dll install\Lib\site-packages\openturns
  - copy C:\Libraries\tbb\bin\tbb.dll install\Lib\site-packages\openturns
  - ctest -C Release --output-on-failure --timeout 100 -E "cppcheck|Sequence|Entropy|Sklar|Sample_computation|InverseBox" -j2 --repeat after-timeout:2 --schedule-random
