version: 2

jobs:
  build_linux:
    docker:
      - image: openturns/archlinux-python
        environment:
          MAKEFLAGS: "-j2"
          OPENTURNS_NUM_THREADS: "2"
    steps:
      - checkout
      - run:
          name: Build and test
          command: ./.circleci/run_docker_linux.sh
      - run:
          name: Publish documentation
          command: ./.circleci/upload_github_io.sh
      - store_artifacts:
          path: ~/.local/share/openturns/doc/html
          destination: html

  build_mingw:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
          OPENTURNS_NUM_THREADS: "2"
    steps:
      - checkout
      - run:
          name: Build and test
          no_output_timeout: 15m
          command: ./.circleci/run_docker_mingw.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      - build_mingw
