version: 2

jobs:
  build_linux:
    docker:
      - image: openturns/archlinux-python
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd /tmp && git clone --depth 1 https://github.com/swig/swig.git && cd swig && ./autogen.sh && ./configure --without-alllang && make && sudo make install
            sudo pip install git+https://github.com/sphinx-doc/sphinx.git
            sudo pip install sphinx-gallery
      - run:
          name: Build and test
          command: ./.circleci/run_docker_linux.sh
      - run:
          name: Publish documentation
          command: ./.circleci/upload_github_io.sh

  build_mingw:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - checkout
      - run:
          name: Build and test
          command: ./.circleci/run_docker_mingw.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      - build_mingw
