version: 2

jobs:
  build_linux:
    working_directory: ~
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            test -n "${CIRCLE_PR_NUMBER}" || sudo add-apt-repository -y ppa:jonathonf/texlive-2016
            sudo apt-get update
            sudo apt-get install -y cmake gfortran bison flex libmuparser-dev liblapack-dev libxml2-dev libboost-math-dev libtbb-dev libnlopt-dev r-base-core
            sudo apt-get install -y python3-pip python3-dev python3-scipy python3-matplotlib texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra pandoc
            sudo rm -r /opt/circleci/.pyenv && sudo pip3 install setuptools --upgrade && pip3 install chaospy matplotlib sphinx numpydoc nbsphinx jupyter_client ipython --user --upgrade
            git clone https://github.com/swig/swig.git && cd swig && git checkout rel-3.0.12 && ./autogen.sh && ./configure --prefix=$HOME/.local --without-alllang && make -j2 && make install
            git clone https://github.com/jeromerobert/hmat-oss.git && cd hmat-oss && git checkout 1.5.0 && cmake -DCMAKE_INSTALL_PREFIX=~/.local . && make install -j2
      - run:
          name: Build and test
          command: SOURCE_DATE_EPOCH=1514761200 && export SOURCE_DATE_EPOCH && ./.circleci/build.sh
      - deploy:
          name: Upload documentation
          command: export GH_TOKEN && ./.circleci/upload_github_io.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
